# wensday_web.py
from fastapi import FastAPI, HTTPException
from fastapi.responses import FileResponse, Response
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel
import os
import httpx

from wensday_voice import ask_wensday  # use the brain you already built

app = FastAPI(title="Wensday OS")


# -------- Models --------
class ChatRequest(BaseModel):
    user_text: str
    voice_mode: bool = False  # for later, when we hook in audio


class ChatResponse(BaseModel):
    reply: str


class TTSRequest(BaseModel):
    text: str


# -------- Chat Route (Wensday brain) --------
@app.post("/chat", response_model=ChatResponse)
async def chat_endpoint(payload: ChatRequest):
    reply = ask_wensday(payload.user_text, voice_mode=payload.voice_mode)
    return ChatResponse(reply=reply)


# -------- ElevenLabs configuration --------
ELEVENLABS_VOICE_ID = os.getenv("ELEVENLABS_VOICE_ID", "l6JdXREaWV2XUOQFjMPH")  # your custom voice ID


# -------- TTS Route (ElevenLabs) --------
@app.post("/tts")
async def tts_endpoint(payload: TTSRequest):
    """
    Takes text from the frontend and returns MP3 audio generated by ElevenLabs
    using your custom voice.
    """
    api_key = os.getenv("ELEVENLABS_API_KEY")
    if not api_key:
        raise HTTPException(status_code=500, detail="ELEVENLABS_API_KEY not set in environment")

    url = f"https://api.elevenlabs.io/v1/text-to-speech/{ELEVENLABS_VOICE_ID}"
    headers = {
        "xi-api-key": api_key,
        "Content-Type": "application/json",
        "Accept": "audio/mpeg",
    }
    body = {
        "text": payload.text,
        "model_id": "eleven_turbo_v2",
        "voice_settings": {
            "stability": 0.5,
            "similarity_boost": 0.8,
        },
    }

    async with httpx.AsyncClient() as client:
        r = await client.post(url, headers=headers, json=body)

    if r.status_code != 200:
        # Print more info to the server console for debugging
        try:
            err_text = r.text
        except Exception:
            err_text = "<no body>"

        print("ElevenLabs TTS error:", r.status_code, err_text[:500])

        raise HTTPException(
            status_code=500,
            detail=f"ElevenLabs error {r.status_code}: {err_text}"
        )

    return Response(content=r.content, media_type="audio/mpeg")


# -------- Static Frontend --------
# Serve the static folder (for CSS/JS if needed)
app.mount("/static", StaticFiles(directory="static"), name="static")


@app.get("/")
async def root():
    # Serve the main HTML UI
    index_path = os.path.join("static", "index.html")
    return FileResponse(index_path)